export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_LANGUAGES_START = "FETCH_LANGUAGES_START";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";
export const FETCH_LANGUAGES_FAIL = "FETCH_LANGUAGES_FAIL";
export const SAVE_LANGUAGE_SUCCESS = "SAVE_LANGUAGE_SUCCESS";
export const RESET_SAVE_LANGUAGE_SUCCESS = "RESET_SAVE_LANGUAGE_SUCCESS";
export const FETCH_LANGUAGE_START = "FETCH_LANGUAGE_START";
export const FETCH_LANGUAGE_SUCCESS = "FETCH_LANGUAGE_SUCCESS";
export const REMOVE_LANGUAGE = "REMOVE_LANGUAGE";
export const UPDATE_LANGUAGE_FAIL = "UPDATE_LANGUAGE_FAIL";
