export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_MENU_START = "FETCH_MENU_START";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_FAIL = "FETCH_MENU_FAIL";

export const FETCH_LANGUAGE_PERMISSIONS_START =
  "FETCH_LANGUAGE_PERMISSIONS_START";
export const FETCH_LANGUAGE_PERMISSIONS_SUCCESS =
  "FETCH_LANGUAGE_PERMISSIONS_SUCCESS";
export const FETCH_LANGUAGE_PERMISSIONS_FAIL =
  "FETCH_LANGUAGE_PERMISSIONS_FAIL";
export const FETCH_LANGUAGES_START = "FETCH_LANGUAGES_START";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";
export const FETCH_LANGUAGES_FAIL = "FETCH_LANGUAGES_FAIL";
export const SAVE_LANGUAGE_SUCCESS = "SAVE_LANGUAGE_SUCCESS";
export const RESET_SAVE_LANGUAGE_SUCCESS = "RESET_SAVE_LANGUAGE_SUCCESS";
export const FETCH_LANGUAGE_START = "FETCH_LANGUAGE_START";
export const FETCH_LANGUAGE_SUCCESS = "FETCH_LANGUAGE_SUCCESS";
