export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SET_TIMER = "AUTH_SET_TIMER";

export const FETCH_LANGUAGES_START = "FETCH_LANGUAGES_START";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";
export const FETCH_LANGUAGES_FAIL = "FETCH_LANGUAGES_FAIL";
export const SAVE_LANGUAGE_SUCCESS = "SAVE_LANGUAGE_SUCCESS";
export const RESET_SAVE_LANGUAGE_SUCCESS = "RESET_SAVE_LANGUAGE_SUCCESS";
export const FETCH_LANGUAGE_START = "FETCH_LANGUAGE_START";
export const FETCH_LANGUAGE_SUCCESS = "FETCH_LANGUAGE_SUCCESS";
export const REMOVE_LANGUAGE = "REMOVE_LANGUAGE";
export const UPDATE_LANGUAGE_FAIL = "UPDATE_LANGUAGE_FAIL";
export const FETCH_LANGUAGES_LOOKUP_START = "FETCH_LANGUAGES_LOOKUP_START";
export const FETCH_LANGUAGES_LOOKUP_SUCCESS = "FETCH_LANGUAGES_LOOKUP_SUCCESS";
export const FETCH_LANGUAGES_LOOKUP_FAIL = "FETCH_LANGUAGES_LOOKUP_FAIL";

export const FETCH_SUBSCRIBERS_START = "FETCH_SUBSCRIBERS_START";
export const FETCH_SUBSCRIBERS_SUCCESS = "FETCH_SUBSCRIBERS_SUCCESS";
export const FETCH_SUBSCRIBERS_FAIL = "FETCH_SUBSCRIBERS_FAIL";
export const SAVE_SUBSCRIBER_SUCCESS = "SAVE_SUBSCRIBER_SUCCESS";
export const RESET_SAVE_SUBSCRIBER_SUCCESS = "RESET_SAVE_SUBSCRIBER_SUCCESS";
export const FETCH_SUBSCRIBER_START = "FETCH_SUBSCRIBER_START";
export const FETCH_SUBSCRIBER_SUCCESS = "FETCH_SUBSCRIBER_SUCCESS";
export const REMOVE_SUBSCRIBER = "REMOVE_SUBSCRIBER";
export const UPDATE_SUBSCRIBER_FAIL = "UPDATE_SUBSCRIBER_FAIL";

export const FETCH_MESSAGES_START = "FETCH_MESSAGES_START";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAIL = "FETCH_MESSAGES_FAIL";
export const SAVE_MESSAGE_SUCCESS = "SAVE_MESSAGE_SUCCESS";
export const RESET_SAVE_MESSAGE_SUCCESS = "RESET_SAVE_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_START = "FETCH_MESSAGE_START";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const UPDATE_MESSAGE_FAIL = "UPDATE_MESSAGE_FAIL";
